language: python
sudo: false
bundler_args: --retry 8

python:
  - 2.7

before_install:
  - pip install --upgrade pip

install:
  - wget https://bootstrap.pypa.io/bootstrap-buildout.py
  - python bootstrap-buildout.py
  - travis_retry bin/buildout

script: bin/py setup.py test -q
